"""update organization logo and theme

Revision ID: 321560b508d3
Revises: d8edbb9aacdb
Create Date: 2026-08-04 12:38:50.871688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '321560b508d3'
down_revision: Union[str, Sequence[str], None] = 'd8edbb9aacdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('LogoURL', sa.String(length=500), nullable=True))
    op.alter_column('organizations', 'Theme',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('LIGHT', 'DARK', 'BLUE', 'GREEN', name='themeenum'),
               nullable=False)
    op.drop_column('organizations', 'Logo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('Logo', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('organizations', 'Theme',
               existing_type=sa.Enum('LIGHT', 'DARK', 'BLUE', 'GREEN', name='themeenum'),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('organizations', 'LogoURL')
    # ### end Alembic commands ###
