"""update models

Revision ID: d8edbb9aacdb
Revises: 665129c3bb56
Create Date: 2026-07-31 14:19:11.245826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8edbb9aacdb'
down_revision: Union[str, Sequence[str], None] = '665129c3bb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_history', 'ActivityDate',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('attachments', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('attachments', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.add_column('comments', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('comments', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.add_column('organization_members', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('organization_members', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.add_column('organizations', sa.Column('Logo', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('Theme', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('organizations', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.add_column('permissions', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('permissions', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.alter_column('permissions', 'RoleID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('project_members', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('project_members', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.add_column('projects', sa.Column('Status', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('projects', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.add_column('roles', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('roles', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('CreatedAt', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('UpdatedAt', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.drop_column('users', 'OrganizationID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('OrganizationID', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'organizations', ['OrganizationID'], ['OrganizationID'])
    op.drop_column('users', 'UpdatedAt')
    op.drop_column('users', 'CreatedAt')
    op.drop_column('tasks', 'UpdatedAt')
    op.drop_column('tasks', 'CreatedAt')
    op.drop_column('roles', 'UpdatedAt')
    op.drop_column('roles', 'CreatedAt')
    op.drop_column('projects', 'UpdatedAt')
    op.drop_column('projects', 'CreatedAt')
    op.drop_column('projects', 'Status')
    op.drop_column('project_members', 'UpdatedAt')
    op.drop_column('project_members', 'CreatedAt')
    op.alter_column('permissions', 'RoleID',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('permissions', 'UpdatedAt')
    op.drop_column('permissions', 'CreatedAt')
    op.drop_column('organizations', 'UpdatedAt')
    op.drop_column('organizations', 'CreatedAt')
    op.drop_column('organizations', 'Theme')
    op.drop_column('organizations', 'Logo')
    op.drop_column('organization_members', 'UpdatedAt')
    op.drop_column('organization_members', 'CreatedAt')
    op.drop_column('comments', 'UpdatedAt')
    op.drop_column('comments', 'CreatedAt')
    op.drop_column('attachments', 'UpdatedAt')
    op.drop_column('attachments', 'CreatedAt')
    op.alter_column('activity_history', 'ActivityDate',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
